# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: Xcode@5
  inputs:
    xcodeVersion: '11' # Options: default, 10, 9, 8, specifyPath

- task: CmdLine@2
  inputs:
    script: |
      bundle install
      xcrun simctl list
      bundle exec fastlane test
