fastlane_version "2.145.0"
default_platform :ios

XCODE_VERSION = "11.4"

platform :ios do

  before_each do
    xcversion(version: "#{XCODE_VERSION}")
    sh 'xcode-select -p'
    sh 'instruments -s devices'
  end

  desc "Runs all the tests"
  lane :test do
    run_tests(
      workspace: "Big Timer.xcworkspace",
      scheme: "Big Timer",
      devices: ["iPhone 11 Pro", "iPad Pro (9.7-inch) (13.4)", "Mac (1412)"]
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "Big Timer") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    increment_version_number(bump_type: "patch")
    match(type: "appstore")
    snapshot
    gym(scheme: "Big Timer")
    deliver(force: true)
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
